import {
  ShippingLoad,
  ShippingCarrier,
  ShippingTrailer,
  CustomerBranding,
  ShippingReceipt,
  ShippingAuditLog,
} from './shipping-types';

export const DEMO_CARRIERS: ShippingCarrier[] = [
  {
    id: 'carr-1',
    name: 'Lone Star Heavy Haul LLC',
    dot_number: 'US DOT 2849102',
    phone: '(512) 555-0199',
    email: 'dispatch@lonestarheavy.com',
    address: '10400 IH-35 North, Round Rock, TX 78665',
    is_active: true,
  },
  {
    id: 'carr-2',
    name: 'Texas Steel Logistics Inc',
    dot_number: 'US DOT 1948201',
    phone: '(713) 555-4820',
    email: 'freight@txsteellogistics.com',
    address: '8200 Market St, Houston, TX 77029',
    is_active: true,
  },
  {
    id: 'carr-3',
    name: 'In-House Fleet (FabSimple Trucking)',
    dot_number: 'US DOT 3104928',
    phone: '(512) 555-9000',
    email: 'transport@fabsimple.com',
    address: '1500 Steel Mill Rd, Taylor, TX 76574',
    is_active: true,
  },
];

export const DEMO_TRAILERS: ShippingTrailer[] = [
  {
    id: 'trail-1',
    trailer_number: 'TR-48-FLAT-01',
    trailer_type: 'FLATBED',
    max_weight_lbs: 48000,
    deck_length_ft: 48,
    is_active: true,
  },
  {
    id: 'trail-2',
    trailer_number: 'TR-53-STEP-04',
    trailer_type: 'STEP_DECK',
    max_weight_lbs: 45000,
    deck_length_ft: 53,
    is_active: true,
  },
  {
    id: 'trail-3',
    trailer_number: 'TR-40-RGN-02',
    trailer_type: 'RGN',
    max_weight_lbs: 65000,
    deck_length_ft: 40,
    is_active: true,
  },
  {
    id: 'trail-4',
    trailer_number: 'TR-53-VAN-09',
    trailer_type: 'DRY_VAN',
    max_weight_lbs: 44000,
    deck_length_ft: 53,
    is_active: true,
  },
];

export const DEMO_CUSTOMER_BRANDING: CustomerBranding = {
  id: 'brand-1',
  company_name: 'Apex Structural Erectors & Fabricators',
  tagline: 'Precision Steel Fabrication & Erection Since 1994',
  logo_url: '/logo-apex.png',
  address: '1500 Steel Mill Rd, Taylor, TX 76574',
  phone: '(512) 555-STEEL (7833)',
  email: 'shipping@apexstructural.com',
  website: 'www.apexstructural.com',
  primary_color: '#0f172a',
  secondary_color: '#3b82f6',
};

export const DEMO_SHIPPING_LOADS: ShippingLoad[] = [
  {
    id: 'load-101',
    ticket_number: 'BOL-2026-0042',
    project_id: 'proj-1',
    project_name: 'Austin High School Expansion',
    job_number: '2024-001',
    status: 'SHIPPED',
    created_at: '2026-09-02T08:30:00Z',
    shipped_at: '2026-09-03T10:15:00Z',
    delivered_at: '2026-09-03T14:30:00Z',

    origin_name: 'Apex Taylor Fab Facility (Bay 3)',
    origin_address: '1500 Steel Mill Rd, Taylor, TX 76574',

    destination_name: 'Jobsite - Austin High School (Gate 2)',
    destination_address: '1715 Cesar Chavez St, Austin, TX 78703',
    destination_contact: 'Dave Miller (Erection Foreman)',
    destination_phone: '(512) 555-8821',

    carrier_name: 'Lone Star Heavy Haul LLC',
    dot_number: 'US DOT 2849102',
    driver_name: 'Marcus Vance',
    driver_phone: '(512) 555-3390',
    truck_number: 'TK-882',
    trailer_number: 'TR-48-FLAT-01',
    trailer_type: 'FLATBED',

    max_weight_lbs: 48000,
    gross_weight_lbs: 54200,
    tare_weight_lbs: 32100,
    net_weight_lbs: 22100,

    bol_notes: 'Must unload with 50-ton mobile crane at North Elevation. Store on dunnage.',
    internal_notes: 'Staged by Yard Crew A on 09/02. All paint dry-to-touch verified.',

    signed_by: 'Dave Miller',
    signed_at: '2026-09-03T14:35:00Z',
    signature_url: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="150" height="40"><path d="M10 25 C30 10, 60 35, 90 15 S130 30, 140 20" stroke="%231e293b" stroke-width="2" fill="none"/></svg>',

    items: [
      {
        id: 'li-1',
        load_id: 'load-101',
        assembly_id: 'asm-101',
        mark: 'B-101',
        qty_on_load: 4,
        unit_weight_lbs: 1850,
        total_weight_lbs: 7400,
        main_material: 'W18X35',
        length_ft_in: "28'-6\"",
        finish: 'GRAY_PRIMER',
        sequence: 'SEQ-1',
        drawing_no: 'S-201',
        bay_location: 'Bay 3 Staging',
        status: 'SHIPPED',
        qc_inspected: true,
      },
      {
        id: 'li-2',
        load_id: 'load-101',
        assembly_id: 'asm-102',
        mark: 'C-201',
        qty_on_load: 2,
        unit_weight_lbs: 4200,
        total_weight_lbs: 8400,
        main_material: 'W14X90',
        length_ft_in: "34'-0\"",
        finish: 'GALVANIZED',
        sequence: 'SEQ-1',
        drawing_no: 'S-101',
        bay_location: 'Bay 3 Staging',
        status: 'SHIPPED',
        qc_inspected: true,
      },
      {
        id: 'li-3',
        load_id: 'load-101',
        assembly_id: 'asm-103',
        mark: 'TR-1',
        qty_on_load: 1,
        unit_weight_lbs: 6300,
        total_weight_lbs: 6300,
        main_material: 'WT6X25 & L4X4X3/8',
        length_ft_in: "45'-0\"",
        finish: 'PAINTED',
        sequence: 'SEQ-1',
        drawing_no: 'S-305',
        bay_location: 'Yard North',
        status: 'SHIPPED',
        qc_inspected: true,
      },
    ],

    additional_items: [
      {
        id: 'ai-1',
        load_id: 'load-101',
        description: '3/4" x 2-1/2" A325 Structural Bolt Kegs',
        qty: 4,
        unit: 'KEGS',
        weight_lbs: 200,
        category: 'BOLTS',
        notes: 'For B-101 & C-201 field connections',
      },
      {
        id: 'ai-2',
        load_id: 'load-101',
        description: 'Gray Primer Spray Cans (Tnemec Series 90-97)',
        qty: 6,
        unit: 'CANS',
        weight_lbs: 12,
        category: 'TOUCHUP_PAINT',
        notes: 'Field touch-up after erection',
      },
      {
        id: 'ai-3',
        load_id: 'load-101',
        description: '4x4 Hardwood Oak Dunnage Timbers',
        qty: 8,
        unit: 'PCS',
        weight_lbs: 180,
        category: 'DUNNAGE',
        notes: 'Ground staging dunnage',
      },
    ],
  },
  {
    id: 'load-102',
    ticket_number: 'BOL-2026-0043',
    project_id: 'proj-1',
    project_name: 'Austin High School Expansion',
    job_number: '2024-001',
    status: 'READY_TO_SHIP',
    created_at: '2026-09-08T11:00:00Z',

    origin_name: 'Apex Taylor Fab Facility (Bay 2)',
    origin_address: '1500 Steel Mill Rd, Taylor, TX 76574',

    destination_name: 'Jobsite - Austin High School (Gate 2)',
    destination_address: '1715 Cesar Chavez St, Austin, TX 78703',
    destination_contact: 'Dave Miller (Erection Foreman)',
    destination_phone: '(512) 555-8821',

    carrier_name: 'Texas Steel Logistics Inc',
    dot_number: 'US DOT 1948201',
    driver_name: 'Robert Thorne',
    driver_phone: '(713) 555-9012',
    truck_number: 'TK-402',
    trailer_number: 'TR-53-STEP-04',
    trailer_type: 'STEP_DECK',

    max_weight_lbs: 45000,

    bol_notes: 'Second beam shipment for Sequence 1 Level 2 framing.',
    internal_notes: 'Staged at Bay 2 loading ramp. QC signoff completed by Tom R.',

    items: [
      {
        id: 'li-4',
        load_id: 'load-102',
        assembly_id: 'asm-104',
        mark: 'B-102',
        qty_on_load: 6,
        unit_weight_lbs: 1420,
        total_weight_lbs: 8520,
        main_material: 'W16X26',
        length_ft_in: "24'-0\"",
        finish: 'GRAY_PRIMER',
        sequence: 'SEQ-1',
        drawing_no: 'S-202',
        bay_location: 'Bay 2 Staging',
        status: 'READY_TO_SHIP',
        qc_inspected: true,
      },
      {
        id: 'li-5',
        load_id: 'load-102',
        assembly_id: 'asm-105',
        mark: 'B-103',
        qty_on_load: 8,
        unit_weight_lbs: 1650,
        total_weight_lbs: 13200,
        main_material: 'W18X35',
        length_ft_in: "26'-4\"",
        finish: 'GRAY_PRIMER',
        sequence: 'SEQ-1',
        drawing_no: 'S-202',
        bay_location: 'Bay 2 Staging',
        status: 'READY_TO_SHIP',
        qc_inspected: true,
      },
      {
        id: 'li-6',
        load_id: 'load-102',
        assembly_id: 'asm-106',
        mark: 'BR-1',
        qty_on_load: 12,
        unit_weight_lbs: 380,
        total_weight_lbs: 4560,
        main_material: 'HSS4X4X1/4',
        length_ft_in: "14'-8\"",
        finish: 'GALVANIZED',
        sequence: 'SEQ-1',
        drawing_no: 'S-401',
        bay_location: 'Paint Yard',
        status: 'READY_TO_SHIP',
        qc_inspected: true,
      },
    ],

    additional_items: [
      {
        id: 'ai-4',
        load_id: 'load-102',
        description: '7/8" A325 Structural Bolts (2-1/4" Length)',
        qty: 2,
        unit: 'KEGS',
        weight_lbs: 110,
        category: 'BOLTS',
      },
    ],
  },
  {
    id: 'load-103',
    ticket_number: 'BOL-2026-0044',
    project_id: 'proj-1',
    project_name: 'Austin High School Expansion',
    job_number: '2024-001',
    status: 'BUILDING',
    created_at: '2026-09-09T09:00:00Z',

    origin_name: 'Apex Taylor Fab Facility',
    origin_address: '1500 Steel Mill Rd, Taylor, TX 76574',

    destination_name: 'Jobsite - Austin High School',
    destination_address: '1715 Cesar Chavez St, Austin, TX 78703',

    carrier_name: 'In-House Fleet (FabSimple Trucking)',
    trailer_type: 'FLATBED',

    max_weight_lbs: 48000,

    bol_notes: 'Sequence 2 Roof Trusses and Girts',

    items: [
      {
        id: 'li-7',
        load_id: 'load-103',
        assembly_id: 'asm-107',
        mark: 'C-202',
        qty_on_load: 4,
        unit_weight_lbs: 3900,
        total_weight_lbs: 15600,
        main_material: 'W14X90',
        length_ft_in: "34'-0\"",
        finish: 'GRAY_PRIMER',
        sequence: 'SEQ-2',
        drawing_no: 'S-102',
        bay_location: 'Bay 1 Machine Shop',
        status: 'BUILDING',
        qc_inspected: false,
      },
    ],
    additional_items: [],
  },
  {
    id: 'load-104',
    ticket_number: 'BOL-2026-0039',
    project_id: 'proj-2',
    project_name: 'Dallas Medical Center Phase 2',
    job_number: '2024-002',
    status: 'DELIVERED',
    created_at: '2026-08-28T07:00:00Z',
    shipped_at: '2026-08-29T06:30:00Z',
    delivered_at: '2026-08-29T11:45:00Z',

    origin_name: 'Apex Taylor Fab Facility',
    origin_address: '1500 Steel Mill Rd, Taylor, TX 76574',

    destination_name: 'Dallas Medical Site - Gate A',
    destination_address: '777 Medical Pkwy, Dallas, TX 75201',
    destination_contact: 'Sam Houston (Site Superintendent)',
    destination_phone: '(214) 555-0911',

    carrier_name: 'Lone Star Heavy Haul LLC',
    driver_name: 'Carlos Ruiz',
    driver_phone: '(512) 555-7733',
    truck_number: 'TK-901',
    trailer_number: 'TR-40-RGN-02',
    trailer_type: 'RGN',

    max_weight_lbs: 65000,
    gross_weight_lbs: 72400,
    tare_weight_lbs: 34000,
    net_weight_lbs: 38400,

    bol_notes: 'Heavy column shipment. Escort vehicle utilized.',

    signed_by: 'Sam Houston',
    signed_at: '2026-08-29T11:50:00Z',

    items: [
      {
        id: 'li-8',
        load_id: 'load-104',
        assembly_id: 'asm-201',
        mark: 'HC-1',
        qty_on_load: 2,
        unit_weight_lbs: 12500,
        total_weight_lbs: 25000,
        main_material: 'W14X176',
        length_ft_in: "42'-0\"",
        finish: 'FIREPROOF_PRIMER',
        sequence: 'SEQ-1',
        drawing_no: 'S-001',
        status: 'DELIVERED',
        qc_inspected: true,
      },
      {
        id: 'li-9',
        load_id: 'load-104',
        assembly_id: 'asm-202',
        mark: 'HC-2',
        qty_on_load: 1,
        unit_weight_lbs: 13400,
        total_weight_lbs: 13400,
        main_material: 'W14X193',
        length_ft_in: "42'-0\"",
        finish: 'FIREPROOF_PRIMER',
        sequence: 'SEQ-1',
        drawing_no: 'S-001',
        status: 'DELIVERED',
        qc_inspected: true,
      },
    ],
    additional_items: [],
  },
];

export const DEMO_AVAILABLE_ASSEMBLIES = [
  {
    id: 'asm-301',
    mark: 'B-201',
    main_material: 'W21X44',
    qty_total: 10,
    qty_shipped: 2,
    qty_staged: 4,
    qty_unshipped: 8,
    unit_weight_lbs: 2150,
    total_weight_lbs: 21500,
    length_ft_in: "30'-0\"",
    finish: 'GRAY_PRIMER',
    sequence: 'SEQ-2',
    drawing_no: 'S-205',
    bay_location: 'Bay 3 Paint Line',
    qc_inspected: true,
  },
  {
    id: 'asm-302',
    mark: 'B-202',
    main_material: 'W24X55',
    qty_total: 6,
    qty_shipped: 0,
    qty_staged: 6,
    qty_unshipped: 6,
    unit_weight_lbs: 2900,
    total_weight_lbs: 17400,
    length_ft_in: "32'-6\"",
    finish: 'GRAY_PRIMER',
    sequence: 'SEQ-2',
    drawing_no: 'S-205',
    bay_location: 'Bay 3 Staging',
    qc_inspected: true,
  },
  {
    id: 'asm-303',
    mark: 'C-301',
    main_material: 'W14X109',
    qty_total: 4,
    qty_shipped: 0,
    qty_staged: 2,
    qty_unshipped: 4,
    unit_weight_lbs: 5100,
    total_weight_lbs: 20400,
    length_ft_in: "36'-0\"",
    finish: 'GRAY_PRIMER',
    sequence: 'SEQ-2',
    drawing_no: 'S-105',
    bay_location: 'Yard Central',
    qc_inspected: true,
  },
  {
    id: 'asm-304',
    mark: 'VB-101',
    main_material: 'L5X5X1/2',
    qty_total: 16,
    qty_shipped: 4,
    qty_staged: 8,
    qty_unshipped: 12,
    unit_weight_lbs: 340,
    total_weight_lbs: 5440,
    length_ft_in: "18'-2\"",
    finish: 'GALVANIZED',
    sequence: 'SEQ-1',
    drawing_no: 'S-402',
    bay_location: 'Galv Storage Yard',
    qc_inspected: true,
  },
  {
    id: 'asm-305',
    mark: 'TS-01',
    main_material: 'HSS8X8X3/8',
    qty_total: 8,
    qty_shipped: 0,
    qty_staged: 0,
    qty_unshipped: 8,
    unit_weight_lbs: 1280,
        total_weight_lbs: 10240,
    length_ft_in: "22'-0\"",
    finish: 'BARE_STEEL',
    sequence: 'SEQ-3',
    drawing_no: 'S-301',
    bay_location: 'Bay 1 Fabrication',
    qc_inspected: false,
  },
];

export const DEMO_RECEIPTS: ShippingReceipt[] = [
  {
    id: 'rec-1',
    load_id: 'load-101',
    ticket_number: 'BOL-2026-0042',
    received_at: '2026-09-03T14:30:00Z',
    received_by: 'Dave Miller',
    condition: 'COMPLETE',
    damage_reported: false,
    signature_url: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="150" height="40"><path d="M10 25 C30 10, 60 35, 90 15 S130 30, 140 20" stroke="%231e293b" stroke-width="2" fill="none"/></svg>',
    notes: 'Received all 7 pieces and 3 accessory items in good condition on site.',
  },
];

export const DEMO_AUDIT_LOGS: ShippingAuditLog[] = [
  {
    id: 'log-1',
    load_id: 'load-101',
    action: 'CREATED',
    timestamp: '2026-09-02T08:30:00Z',
    user_name: 'John Fabricator',
    details: 'Created load BOL-2026-0042 for Austin High School Expansion',
  },
  {
    id: 'log-2',
    load_id: 'load-101',
    action: 'QC_VERIFIED',
    timestamp: '2026-09-02T16:00:00Z',
    user_name: 'Tom QC Manager',
    details: 'Verified all 7 assemblies and accessories staged in Bay 3',
  },
  {
    id: 'log-3',
    load_id: 'load-101',
    action: 'SHIPPED',
    timestamp: '2026-09-03T10:15:00Z',
    user_name: 'Yard Master Pete',
    details: 'Dispatched with carrier Lone Star Heavy Haul (Driver: Marcus Vance)',
  },
  {
    id: 'log-4',
    load_id: 'load-101',
    action: 'DELIVERED',
    timestamp: '2026-09-03T14:30:00Z',
    user_name: 'Dave Miller (Erector)',
    details: 'Signed for load on jobsite in complete condition',
  },
];
